### ISSUE TITLE
where the data(cifar10-lt_train.npz) from?

### ISSUE THREAD

**Issue by limengyang1992** [Chumsy0725/logit-adj-pytorch#1]
hello~, where the data(cifar10-lt_train.npz) from?    Are there other proportions of long tail data?

**Comment by chandeepadissanayake** [comment]
If you need the dataset files you can find them under the data directory.
They've been inferred from the tfrecord dataset at [](https://github.com/google-research/google-research/tree/master/logit_adjustment)

We've followed the exact same propotions as given in the original research work by Google Research.
[](https://arxiv.org/abs/2007.07314)
